### ISSUE TITLE
NOT WORKING ANYMORE

### ISSUE THREAD

**Issue by rajesh-fa** [forgetso/search-replace#108]
**Describe the bug**
Please provide the following information:
- Search and Replace Version: 2.0.4
- Web page URL: All
- Options checked (`Input fields only` etc.):

This Extension is No longer working.

**Comment by CrystalSchmidt** [comment]
Agree this is not working anymore. Is there a ETA on these bug fixes after the new release? Any chance you could revert to the working version? This extension has been SO helpful at work and I'm coming up to a deadline. TIA!

**Comment by forgetso** [comment]
Hi Both, thanks for the report. I will either revert or post the old version online so that you can revert to it manually by [loading an unpacked extension in Chrome](https://superuser.com/a/247654/174115).

In the meantime, please provide anything you can that will help me replicate the issue that you're having:

**Describe the bug**
Please provide the following information:
- Search and Replace Version: 2.0.4
- Web page URL: **THIS IS CRITICAL TO BE ABLE TO REPLICATE THE PROBLEM**
- Options checked (`Input fields only` etc.):

**Attach a copy of the problem web page** - **THIS IS VERY HELPFUL**
Attach a copy of the problem page downloaded by using [this chrome extension to download it](https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en).

Thanks, I'll update in the next couple of days with instructions on how to downgrade!

**Comment by forgetso** [comment]
Hi, you can download the old version (1.7.4) [here](https://github.com/forgetso/search-replace/releases/download/1.7.4/search_and_replace_1.7.4.zip). You will need to load it using the [unpacked method in Chrome](https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/).

I'm not going to downgrade the version in the Chrome extension store until I have details that I can replicate, as the 2.x.x versions have fixes for *other* bugs that I don't want to remove.There will be another version (2.0.6) live soon, which may resolve the error in which the extension fails to count search occurrences. However, in order to properly investigate *I really need more debug information from someone who's hitting the problem*.

Hope this helps.

**Comment by forgetso** [comment]
Hi, please try version 2.0.8. I think it will fix it for you. Please feel free to re-open this ticket if it is not fixed. Thanks
